services:
  - type: web
    name: whatsapp-sender-server
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: whatsapp-db
    databaseName: whatsapp_licenses
    user: whatsapp_user
    plan: free
